@startuml exercicio
left to right direction

actor "Academico" as acad
actor "Estudante" as est
actor "Professor" as prof
actor "Portal MEC" as mec

est --|> acad
prof --|> acad 

rectangle "SmartBiblio"{
  usecase "Buscar livros" as buscarLivros
  usecase "Registrar retirada" as regRetirada
  usecase "Devolver livros" as devolverLivros
  usecase "Quitar valores pendentes" as quitarValores
  usecase "Entrar na fila de espera" as entrarEspera
  
  usecase "Agendar cabine" as agendarCabine
  usecase "Indicar livros" as indicarLivros
  
  usecase "Comprovar Matricula" as comprovarMatricula
  usecase "Vasculhar historico" as vasculharHistorico
  usecase "Alertar diretoria sobre custo" as alertarDiretoria
  usecase "Imprimir Comprovante" as imprimirComprovante
  usecase "Suspender conta" as suspenderConta
}

acad -- buscarLivros
acad -- regRetirada
acad -- devolverLivros

est -- agendarCabine
prof -- indicarLivros
mec -up- comprovarMatricula

'Dependências: include'
regRetirada ..> comprovarMatricula : <<include>>
agendarCabine ..> comprovarMatricula : <<include>>
indicarLivros ..> comprovarMatricula : <<include>>
regRetirada .right.> vasculharHistorico : <<include>>
agendarCabine .right.> vasculharHistorico : <<include>>

'Dependências: extends'
entrarEspera .up.> buscarLivros: <<extends>>
quitarValores .up.> devolverLivros : <<extends>>
alertarDiretoria .up.> indicarLivros : <<extends>>
suspenderConta .up.> vasculharHistorico : <<extends>>
imprimirComprovante .up.> quitarValores :<<extends>>
imprimirComprovante .up.> regRetirada : <<extends>>

@enduml

